@baseUrl = http://localhost:5000/api/v1
# Update one user by user id

PUT {{baseUrl}}/users/64416d38a9d07d3c6df27c7b
Content-Type: application/json

{
    "email": "fluoo.adm@gmail.com",
    "password": "12345678",
    "type": "registered",
    "email_verified": true,
    "password_reset_token_attempts": 0,
    "name": "fluoo",
    "avatar_url": "https://images.unsplash.com/photo-1464802686167-b939a6910659?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1450&q=80"
}