@baseUrl = http://localhost:5000
@JWTToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2ZmYzc3ZjMxMmE4YzJjZDYyMWFiNTAiLCJ0eXBlIjoicmVnaXN0ZXJlZCIsImVtYWlsIjoiZmVsaXBlLnQudi5kQGdtYWlsLmNvbSIsIm5hbWUiOiJGZWxpcGUiLCJhdmF0YXJfdXJsIjoiaHR0cHM6Ly9xdWFxLWltYWdlLnMzLnNhLWVhc3QtMS5hbWF6b25hd3MuY29tL2Y0ZWE4Y2FhLWQ5NjItNDY1Ni04N2FmLWY1OTY0ZmQ0ZGVjOS1Qcm9maWxlLmpwZyIsImlhdCI6MTY3OTc3MzI0NiwiZXhwIjoxNjc5ODkzMjQ2fQ._TPhlXYECitf3hdg8K8US6UzZ3EM8PQ3wNGYzZHYYBQ

POST {{baseUrl}}/api/v1/templates
Content-Type: application/json
Authorization: {{JWTToken}}

{
  "title": "title",
  "slug": "meutemplate2",
  "shortcut_image": "https://images.unsplash.com/photo-1464802686167-b939a6910659?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1450&q=80",
  "shortcut_size": "small",
  "current_publication_id": "640126c787bd902ed86e2808",
  "number_of_new_interactions": 1,
  "page_id": "64038c1bdd7a747f55a01c03"
}