@baseUrl = http://localhost:5000/api/v1

# Authenticate user
POST {{baseUrl}}/entrypoint/interaction/123456789
Content-Type: application/json

{
    "secret": "123456789",
    "user_id": "63ffc767312a8c2cd621ab4f",
    "data": [{ "test": "test" }],
    "date_of_consensus": "2023-03-08T15:03:56.210+00:00"
}