@baseUrl = http://localhost:5000
@JWTToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDQyZDRlNTlkY2I2ODJhMmE4NTMzN2UiLCJ0eXBlIjoidmlzaXRhbnQiLCJlbWFpbCI6IiIsIm5hbWUiOiIiLCJhdmF0YXJfdXJsIjoiIiwiaWF0IjoxNjgyMTAxNDc3LCJleHAiOjE2ODIyMjE0Nzd9.WqZM83WEJNbvXfFLg1gB-QqQe5Yy76uaXgx8g9oEekY

# Find one workspace by workspace id

GET {{baseUrl}}/api/v1/workspaces/63ffcb458a60bbf52e188e23
Authorization: {{JWTToken}}