@baseUrl = http://localhost:5000
@JWTToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2ZmYzc3ZjMxMmE4YzJjZDYyMWFiNTAiLCJlbWFpbCI6ImZlbGlwZS50LnYuZEBnbWFpbC5jb20iLCJuYW1lIjoiRmVsaXBlIiwiYXZhdGFyX3VybCI6Imh0dHBzOi8vcXVhcS1maWxlcy5zMy5zYS1lYXN0LTEuYW1hem9uYXdzLmNvbS9lNDhjYTQ1My1iZDMzLTRmMTUtYjFkYy0zMTMxY2YwOGI2ZmYtUHJvZmlsZS5qcGciLCJ3b3Jrc3BhY2VzIjpbeyJpZCI6IjYzZmZjYjQ1OGE2MGJiZjUyZTE4OGUyMyIsInNsdWciOiJxdWFxLWFkbSIsIlBhZ2UiOlt7ImlkIjoiNjQwMTE5M2E4OTUyMzAyYzE5NjZlNGE0Iiwic2x1ZyI6InF1YXEifSx7ImlkIjoiNjQwMzg1MTE5NjQ2NTczZTcyNjcxYTRkIiwic2x1ZyI6InRlc3QifV19LHsiaWQiOiI2NDAzOGJlNjY3MTg1YTI3NDc4OGNmOGEiLCJzbHVnIjoibmluZXRoIiwiUGFnZSI6W119LHsiaWQiOiI2NDAzOGMwZGRkN2E3NDdmNTVhMDFiZmYiLCJzbHVnIjoidGVudGgiLCJQYWdlIjpbeyJpZCI6IjY0MDM4YzFiZGQ3YTc0N2Y1NWEwMWMwMyIsInNsdWciOiJ0ZXN0aW5obyJ9XX1dLCJpYXQiOjE2NzgxMjc0MTYsImV4cCI6MTY3ODI0NzQxNn0.9qlfCt2sgWtEyb4LQSm812FPJh3sAzaT06Lv25-GaM8
# Update one workspace by workspace id

PUT  {{baseUrl}}/api/v1/workspaces/63ffcb458a60bbf52e188e23
Content-Type: application/json

{
  "avatar_url": "https://images.unsplash.com/photo-1464802686167-b939a6910659?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1450&q=80"
}