# Variables
@baseUrl = https://bff.quaq.me

# Authenticate user
POST {{baseUrl}}api/v1/auth/login
Content-Type: application/json

{
    "email": "felipe.t.v.d@gmail.com",
    "password": "12345678"
}

###

GET {{baseUrl}}api/v1/auth/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2ZmYzc2NzMxMmE4YzJjZDYyMWFiNGYiLCJlbWFpbCI6ImljYXJsb3NyaWdvbmlAZ21haWwuY29tIiwibmFtZSI6InN0cmluZyIsImF2YXRhcl91cmwiOiJzdHJpbmciLCJpYXQiOjE2Nzc3MDcyNDYsImV4cCI6MTY3NzgyNzI0Nn0.mQ9Bd7PGAmJvtdO5CIxNXqbNF0rCj1-3DWtPXInu0Go