# Variables
@baseUrl = https://bff.quaq.me

# Find one file by file id

GET {{baseUrl}}/api/v1/files/63d2b1a166402037076c063d

###

# Create one file

POST {{baseUrl}}/api/v1/files
Content-Type: application/json

{
    "name": "test",
    "url": "1",
    "type": "image",
    "size": 1000,
    "mime_type": "image/jpeg",
    "metadata": {
        "key": "value"
    }
}

###

# Find one file by file url

GET {{baseUrl}}/file/url/1

###

# Update one file by file id

PUT {{baseUrl}}/file/63b34032485edc50f1bdfa72
Content-Type: application/json

{
    "name": "test2",
    "url": "2",
    "type": "image2",
    "size": 2000,
    "mime_type": "image/png",
    "metadata": {
        "key": "value2"
    }
}

###

# Delete one file by file id

DELETE {{baseUrl}}/file/63b34032485edc50f1bdfa72