# Variables
@baseUrl = https://bff.quaq.me

# Find one interaction by interaction id

GET {{baseUrl}}/api/v1/interactions/63ea847f8d4ff3f2739df2db

###

# Create one interaction
POST {{baseUrl}}/api/v1/interactions
Content-Type: application/json

{
  "blocks": [
    {
      "id": "1",
      "type": "text",
      "data": "digite aqui"
    },
    {
      "id": "2",
      "type": "text",
      "data": "<h1>{{input__placeholder}}ok</h1>"
    },
    {
      "id": "3",
      "type": "textentry",
      "data": {
        "type": "email",
				"value": "dasdasdadadssa"
      }
    }
  ],
  "data": [
    {
      "id": "3",
      "type": "textentry",
      "data": {
        "type": "email",
        "value": "deu certo"
      }
    }
  ],
  "events": [],
  "template_id": "63eebb65f5c834d3a9154bc0",
  "publication_id": "63efbfa074410fc6df8e0d89",
  "page_id": "63df08bef243bdc4870d6b09",
  "user_id": "63d26f06ea1e68c873e97ab2"
}

###

# Find one interaction by user id
GET {{baseUrl}}/interaction/user/63b75045a43fc9f320321e9f

###

# Find one interaction by page id
GET {{baseUrl}}/interaction/page/63b75045a43fc9f320321e9f


###

# Find one interaction by publication id
GET {{baseUrl}}/api/v1/interactions/publication/63efbfa074410fc6df8e0d89

###

# Find one interaction by template id
GET {{baseUrl}}/api/v1/interactions/template/63b75045a43fc9f320321e9f

###

# Update one interaction by interaction id
PUT {{baseUrl}}/api/vi/interactions/63ee9aa429576d089a4a2c95
Content-Type: application/json

{
    "blocks": [
        {
            "type": "text2",
            "text": "Hello world2"
        }
    ]
}