# find one

GET https://bff.quaq.me/api/v1/interactions/63e108d757d857994c68c052

###

# create one
POST https://bff.quaq.me/api/v1/interactions
Content-Type: application/json

{
  "blocks": [
    {
      "id": "1",
      "type": "text",
      "data": "digite aqui"
    },
    {
      "id": "2",
      "type": "text",
      "data": "<h1>{{input__placeholder}}ok</h1>"
    },
    {
      "id": "3",
      "type": "textentry",
      "data": {
        "type": "email"
      }
    }
  ],
  "data": [
    {
      "id": "3",
      "type": "textentry",
      "data": {
        "type": "email",
        "value": "adsadasaaa"
      }
    }
  ],
  "events": [],
  "template_id": "63e00e52bb60a04fa845a3c9",
  "publication_id": "63e103c957d857994c68c04d",
  "page_id": "63e00e16bb60a04fa845a3c8",
  "user_id": "63d26f06ea1e68c873e97ab2"
}

###

# find one by user id
GET https://bff.quaq.com.br/interaction/user/63b75045a43fc9f320321e9f

###

# find one by page id
GET https://bff.quaq.com.br/interaction/page/63b75045a43fc9f320321e9f


###

# find one by publication id
GET https://bff.quaq.com.br/interaction/publication/63b75045a43fc9f320321e9f

###

PUT https://bff.quaq.com.br/interaction/63b758b9aca8210f48db934b
Content-Type: application/json

{
    "blocks": [
        {
            "type": "text2",
            "text": "Hello world2"
        }
    ]
}