# find one

GET http://localhost:5000/api/v1/pages/63e00e16bb60a04fa845a3c8


###

# create one

POST http://localhost:5000/api/v1/pages
Content-Type: application/json

{
    "name": "page 1",
    "url": "minhapagina2",
    "workspace_id": "63b34032485edc50f1bdfa72",
    "avatar_url": "url/url",
    "background_url": "url/url"
}

###

# find all

GET https://bff.quaq.com.br/page

###

# find one by url

GET http://localhost:5000/api/v1/pages/url/minhapagina

###

# find all by workspace

GET https://bff.quaq.com.br/page/workspace/63b34032485edc50f1bdfa72

###

# update one

PUT http://localhost:5000/api/v1/pages/63e00e16bb60a04fa845a3c8
Content-Type: application/json

{
    "name": "quaq",
    "url": "minhapagina",
    "avatar_url": "https://images.unsplash.com/photo-1674225636667-0e12bccc2b4a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    "background_url": "https://images.unsplash.com/photo-1674225636667-0e12bccc2b4a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    "is_stripe_active": false
}

###

# delete one

DELETE https://bff.quaq.com.br/page/63b75045a43fc9f320321e9f



###

# generate unique url

POST http://localhost:5000/api/v1/pages/generate_unique_url
Content-Type: application/json

{
    "name": "adm1"
}
