# find one

GET https://bff.quaq.com.br/page/63b75045a43fc9f320321e9f


###

# create one

POST http://localhost:3000/api/v1/pages
Content-Type: application/json

{
    "name": "page 1",
    "url": "url",
    "workspace_id": "63b34032485edc50f1bdfa72",
    "avatar_url": "url/url",
    "background_url": "url/url"
}

###

# find all

GET https://bff.quaq.com.br/page

###

# find one by url

GET https://bff.quaq.com.br/page/url/url21

###

# find all by workspace

GET https://bff.quaq.com.br/page/workspace/63b34032485edc50f1bdfa72

###

# update one

PUT http://localhost:3000/api/v1/pages/63d59c0acf99580306310382
Content-Type: application/json

{
    "name": "page 12",
    "url": "url2fsdfsd21d",
    "avatar_url": "url/url1",
    "background_url": "url/url",
    "is_stripe_active": true
}

###

# delete one

DELETE https://bff.quaq.com.br/page/63b75045a43fc9f320321e9f



###

# generate unique url

POST http://localhost:5000/api/v1/pages/generate_unique_url
Content-Type: application/json

{
    "name": "adm1"
}