# get publication

GET  https://bff.quaq.me/api/v1/publications/63e059f8a3264c4698093527

###

# create publication


POST http://localhost:5000/api/v1/publications
Content-Type: application/json

{
    "title": "title2",
    "blocks": [{
			"id": "1",
			"type": "text",
			"data": "{{input__placeholder}}"
		}, {
			"id": "2",
			"type": "text",
			"data": "<h1>{{input__placeholder}}</h1>"
		}],
    "page_id": "63e00e16bb60a04fa845a3c8",
		"template_id": "63e00e52bb60a04fa845a3c9"
}

###

# get many publication by template id

GET https://bff.quaq.com.br/publication/template/1

###

# get many publication by page id

GET https://bff.quaq.com.br/publication/page/1

###

# update publication

PUT http://localhost:3000/api/v1/publications/63d5cd37f090a8a5e12a1a5c
Content-Type: application/json

{
    "title": "title1",
    "blocks": {
        "1": {
            "id": "1",
            "type": "type",
            "content": "content"
        }
    }
}