# get template

GET https://bff.quaq.com.br/template/63ae050ffbbce66bbc152486

###

POST http://localhost:5000/api/v1/templates
Content-Type: application/json

{
  "name": "name",
  "url": "meutemplate",
  "shortcut_image": "shortcutImage",
  "shortcut_size": "shortcutSize",
  "current_publication_id": "63e00c3ca62ce469e303482d",
  "number_of_new_interactions": 1,
  "page_id": "63e00e16bb60a04fa845a3c8"
}

###

# get template by url

GET https://bff.quaq.com.br/template/url/url

###

# get many template by page id

GET http://localhost:5000/api/v1/templates/page/63dfc3427d66dd08288f9a1

###

# get many template by page url and template url

GET http://localhost:5000/api/v1/templates/minhapagina/meutemplate

###

PUT https://bff.quaq.com.br/template/63d1bcbe0fd30006d0e22f1c
Content-Type: application/json

{
  "name": "nameddd",
  "url": "urdddddddddl",
  "shortcut_image": "shortcutImage",
  "shortcut_size": "shortcutSize",
  "number_of_new_interactions": 1
}

###

# delete one template

DELETE https://bff.quaq.com.br/template/1ead50e3-c81b-4a64-87da-a1ff0f2e6b54

###

