# Variables
@baseUrl = https://bff.quaq.me

# Find one template by template id

GET {{baseUrl}}/api/v1/templates/63efc46ba52e71db610d72bb
request: logs

###

POST {{baseUrl}}/api/v1/templates
Content-Type: application/json

{
  "name": "name",
  "slug": "meutemplate2",
  "shortcut_image": "shortcutImage",
  "shortcut_size": "shortcutSize",
  "current_publication_id": "63e7cf7388e2141604e1f88e",
  "number_of_new_interactions": 1,
  "page_id": "63e00e16bb60a04fa845a3c8"
}



###

# Find one template by template slug

GET {{baseUrl}}/templates/slug/testess

###

# Find many templates by page id

GET {{baseUrl}}/api/v1/templates/page/63eebb65f5c834d3a9154bc0

###

# Find one page and template by page and template slug

GET http://localhost:5000/api/v1/templates/testinhoa/test
###

PUT {{baseUrl}}/api/v1/templates/63e00e52bb60a04fa845a3c9
Content-Type: application/json

{
  "shortcut_image": "https://images.unsplash.com/photo-1674225636667-0e12bccc2b4a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80"
}

###

# Delete one template by template id

DELETE {{baseUrl}}/api/v1/templates/63f3c6d5d8bd9436af2cbdec


###

# Generate template unique slug

POST {{baseUrl}}/api/v1/templates/generate_unique_slug
Content-Type: application/json


{
  "title": "name",
  "page_id": "63e00e16bb60a04fa845a3c8"

}