# get template

GET https://bff.quaq.com.br/template/63ae050ffbbce66bbc152486

###

POST http://localhost:5000/api/v1/templates
Content-Type: application/json

{
  "name": "name",
  "url": "meutemplate",
  "shortcut_image": "shortcutImage",
  "shortcut_size": "shortcutSize",
  "current_publication_id": "63e00c3ca62ce469e303482d",
  "number_of_new_interactions": 1,
  "page_id": "63e00e16bb60a04fa845a3c8"
}



###

# get template by url

GET https://bff.quaq.com.br/template/url/url

###

# get many template by page id

GET http://localhost:5000/api/v1/templates/page/63e00e16bb60a04fa845a3c8

###

# get  template by page url and template url

GET http://localhost:5000/api/v1/templates/minhapagina/meutemplate

###

PUT https://bff.quaq.com.br/api/v1/templates/63e00e52bb60a04fa845a3c9
Content-Type: application/json

{
  "shortcut_image": "https://images.unsplash.com/photo-1674225636667-0e12bccc2b4a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80"
}

###

# delete one template

DELETE https://bff.quaq.me/api/v1/templates/63e14a4dcf10c7e6a53b2a10


###


POST https://bff.quaq.me/api/v1/templates/generate_unique_url
Content-Type: application/json


{
  "title": "name",
  "page_id": "63e00e16bb60a04fa845a3c8"

}