# find one

GET http://localhost:3000/api/v1/users/63d7195b8efd06bc4047296b

###

# create one

POST http://localhost:3000/api/v1/users/
Content-Type: application/json

{
     "email": "icarlosrigoni@gmail.com",
     "password": "1234578"
}

###

# update one

PUT http://localhost:3000/api/v1/users/63d7195b8efd06bc4047296b
Content-Type: application/json

{
    "email": "icarlosrigoni@gmail.com",
    "password": "1234578",
    "type": "registered",
    "email_verified": true,
    "password_reset_token_attempts": 5,
    "name": "string",
    "avatar_url": "string"

}


###

# delete one

DELETE https://bff.quaq.com.br/user/63b6ed226e2cf11afe9f163c
