
POST http://localhost:5000/api/v1/variables
Content-Type: application/json

{
    "creator_id": "63d7195b8efd06bc4047296b",
		"blocks": [
			{
				"id": "1",
				"type": "textentry",
				"save_as": "blocoteste",
				"data": {
					"type": "email"
				}
			}
		],
		"template_id": "63e7cf8388e2141604e1f88f",
		"connected_templates": ["63e7cf8388e2141604e1f88f", "63ae050ffbbce66bbc152486"]
}
