# Variables
@baseUrl = https://bff.quaq.me

# Find one workspace by workspace id

GET {{baseUrl}}/api/v1/workspaces/63ffcb458a60bbf52e188e23

###

# Create one workspace

POST  {{baseUrl}}/api/v1/workspaces
Content-Type: application/json

{
  "title": "quaq adm",
  "avatar_url": "https://images.unsplash.com/photo-1464802686167-b939a6910659?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1450&q=80",
	"slug": "quaq-adm",
  "services": [
    {
      "name": "basic",
      "description": "basic"
    }
  ]
}

###

# Update one workspace by workspace id

PUT  {{baseUrl}}/api/v1/workspaces/63ffcb458a60bbf52e188e23
Content-Type: application/json

{
  "avatar_url": "https://images.unsplash.com/photo-1464802686167-b939a6910659?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1450&q=80"
}

###

# Delete one workspace by workspace id

DELETE https://bff.quaq.com.br/api/v1/workspace/63b7543e7d02f98b8692255d

###

# Find many workspaces by user id

GET {{baseUrl}}/api/v1/workspaces/user/63d26f06ea1e68c873e97ab2


###

# Find one workspace by workspace slug

GET {{baseUrl}}/api/v1/workspaces/slug/quaq-adm


###

# Find one workspace by page slug

GET {{baseUrl}}/api/v1/workspaces/page/slug/quaq


###

# Generate unique workspace slug

POST {{baseUrl}}/api/v1/workspaces/generate_unique_slug
Content-Type: application/json

{
    "name": "adm1"
}


###

# Add new member to workspace

POST {{baseUrl}}/api/v1/workspaces/members/add/63ffcb458a60bbf52e188e23
Content-Type: application/json

{
    "email": "felipe.t.v.d@gmail.com"
}

###

# Remove exising member from workspace

POST {{baseUrl}}/api/v1/workspaces/members/remove/63ffcb458a60bbf52e188e23
Content-Type: application/json

{
    "user_id": "63ffc77f312a8c2cd621ab50"
}