# find one

GET https://bff.quaq.me/api/v1/workspaces/63e3def89fb620ad10c31742

###

# create one

POST  http://bff.quaq.me/api/v1/workspaces
Content-Type: application/json

{
  "name": "My Workspace",
  "avatar_url": "http://example.com/avatar.png",
	"slug": "tesdddasastae",
  "services": [
    {
      "name": "My Service",
      "description": "My Service Description"
    }
  ]
}

###

# update one

PUT  https://localhost:5000/workspace/63b7543e7d02f98b8692255d
Content-Type: application/json

{
  "name": "My Workspace2",
  "avatar_url": "http://example.com/avatar2.png",
	"slug": "teste",
  "services": [
    {
      "name": "My Service2",
      "description": "My Service Description"
    }
  ]
}

###

# delete one

DELETE https://bff.quaq.com.br/workspace/63b7543e7d02f98b8692255d

###

# get workspace by user id

GET http://localhost:5000/api/v1/workspaces/user/63d26f06ea1e68c873e97ab2


###

# get workspace by slug

GET https://bff.quaq.me/api/v1/workspaces/slug/tesdddasastae


###

# get workspace by page slug

GET https://bff.quaq.me/api/v1/workspaces/page/slug/quaq


###

# generate unique slug workspace

POST http://localhost:5000/api/v1/workspaces/generate_unique_slug
Content-Type: application/json

{
    "name": "adm1"
}
