@baseUrl = http://localhost:5000/api/v1
@JWTToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDQ0NjI5N2VmMTNlMDljMDA0YmQ1MzgiLCJ0eXBlIjoidmlzaXRhbnQiLCJlbWFpbCI6IiIsIm5hbWUiOiIiLCJhdmF0YXJfdXJsIjoiIiwiaWF0IjoxNjgyMjAzMjg3LCJleHAiOjE2ODIzMjMyODd9.kQAaF1a1F8OY8X7-CF83Rh11ewSdVvkRSb1eB6kfe48

# Create one interaction
POST {{baseUrl}}/interactions
Authorization: {{JWTToken}}
Content-Type: application/json

{
  "blocks": [
    {
      
    }
  ],
  "data": [
    {
    }
  ],
  "events": [],
  "template_id": "644057a7aa8e86f617a0631e",
  "publication_id": "644057a6aa8e86f617a0631d",
  "page_id": "6401193a8952302c1966e4a4",
  "user_id": "63ffc77f312a8c2cd621ab50"
}