@baseUrl = https://api.quaq.me

# Create one interaction
POST {{baseUrl}}/api/v1/interactions
Content-Type: application/json

{
  "blocks": [
    {
      "id": "1",
      "type": "text",
      "data": "digite aqui"
    },
    {
      "id": "2",
      "type": "text",
      "data": "<h1>{{input__placeholder}}ok</h1>"
    },
    {
      "id": "3",
      "type": "textentry",
      "data": {
        "type": "email",
				"value": "dasdasdadadssa"
      }
    }
  ],
  "data": [
    {
      "id": "3",
      "type": "textentry",
      "data": {
        "type": "email",
        "value": "deu certo"
      }
    }
  ],
  "events": [],
  "template_id": "63eebb65f5c834d3a9154bc0",
  "publication_id": "63efbfa074410fc6df8e0d89",
  "page_id": "63df08bef243bdc4870d6b09",
  "user_id": "63d26f06ea1e68c873e97ab2"
}