@baseUrl = http://localhost:5000/api/v1
@JWTToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDQyZWEzNjc0NWZjNjE2ZTE1ODA5NDIiLCJ0eXBlIjoidmlzaXRhbnQiLCJlbWFpbCI6IiIsIm5hbWUiOiIiLCJhdmF0YXJfdXJsIjoiIiwiaWF0IjoxNjgyMTA2OTM0LCJleHAiOjE2ODIyMjY5MzR9.gbTKi8K03zmbNuNDh4hNxFrSkwhRm3q64paykcd05QU

# find all by workspace
GET {{baseUrl}}/pages/workspace/63ffcb458a60bbf52e188e23
Authorization: {{JWTToken}}