@baseUrl = http://localhost:5000/api/v1
@JWTToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2ZmYzc3ZjMxMmE4YzJjZDYyMWFiNTAiLCJ0eXBlIjoicmVnaXN0ZXJlZCIsImVtYWlsIjoiZmVsaXBlLnQudi5kQGdtYWlsLmNvbSIsIm5hbWUiOiJGZWxpcGUiLCJhdmF0YXJfdXJsIjoiaHR0cHM6Ly9xdWFxLWltYWdlLnMzLnNhLWVhc3QtMS5hbWF6b25hd3MuY29tL2Y0ZWE4Y2FhLWQ5NjItNDY1Ni04N2FmLWY1OTY0ZmQ0ZGVjOS1Qcm9maWxlLmpwZyIsImlhdCI6MTY4MjE3OTczOSwiZXhwIjoxNjgyMjk5NzM5fQ.1OZ8SY3ebtm_9JzKqM-IQKCc6LNB1uJv-8oG9yyTcEg

# find all by workspace
GET {{baseUrl}}/pages/workspace/63ffcb458a60bbf52e188e23
Authorization: {{JWTToken}}