# find one

GET http://localhost:3000/page/63b75045a43fc9f320321e9f


###

# create one

POST http://localhost:3000/page
Content-Type: application/json

{
    "name": "page 1",
    "url": "url/url1",
    "workspace_id": "63b34032485edc50f1bdfa72",
    "avatar_url": "url/url",
    "background_url": "url/url"
}

###

# find all

GET http://localhost:3000/page

###

# find one by url

GET http://localhost:3000/page/url/url21

###

# find all by workspace

GET http://localhost:3000/page/workspace/63b34032485edc50f1bdfa72

###

# update one

PATCH http://localhost:3000/page/63b75045a43fc9f320321e9f
Content-Type: application/json

{
    "name": "page 1",
    "url": "url21",
    "workspace_id": "63b34032485edc50f1bdfa72",
    "avatar_url": "url/url1",
    "background_url": "url/url",
    "is_stripe_active": true,
    "facebook_pixel_id": "123456789",
    "google_analytics_id": "123456789"
}

###

# delete one

DELETE http://localhost:3000/page/63b75045a43fc9f320321e9f


